[package]
name = "dsh-web-search-deepseek"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "DeepSeek official web search provider."

[dependencies]
async-trait.workspace = true
dsh-cordis.workspace = true
dsh-credentials.workspace = true
dsh-session.workspace = true
dsh-web.workspace = true
serde_json.workspace = true
tokio.workspace = true
