[package]
name = "dsh-fs-observation-policy"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Event-only filesystem observation policy."

[dependencies]
dsh-cordis.workspace = true
dsh-fs.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
